### ISSUE TITLE
Same location, but different events

### ISSUE THREAD

**Issue by jddurand** [jeffreykegler/Marpa--R2#235]
I know location 0 is very special, still I ask if it is correct to have different events at same location (0 in this case):

```
#!env perl
use strict;
use diagnostics;
use Marpa::R2;

print "\$Marpa::R2::VERSION is $Marpa::R2::VERSION\n\n";

our $DATA = do {local $/; <DATA>};
my $g = Marpa::R2::Scanless::G->new({source => \$DATA});
my $r = Marpa::R2::Scanless::R->new({grammar => $g});

my $input = 'not important';

print "\$r->read(\$input)\n";
my $pos = $r->read(\$input);
showInfo($r);

print "\$r->resume($pos)\n";
$pos = $r->resume($pos);
showInfo($r);


sub showInfo {
  my$r = shift;
  print "\tPosition: $pos, G1 location: " . $r->current_g1_location() . ", events: " . join(', ', map {$_->[0]} @{$r->events}) . "\n";
}

__DATA__
event '^first' = predicted <first>
:start ::= first

first ::= NOTHING | ANYTHING

:lexeme ~ <ANYTHING> pause => before event => '^ANYTHING'
ANYTHING         ~ [\s\S]
NOTHING          ~ [^\s\S]
```

produces this output:

```
$Marpa::R2::VERSION is 2.102

$r->read($input)
        Position: 0, G1 location: 0, events: ^first
$r->resume(0)
        Position: 0, G1 location: 0, events: ^ANYTHING
```

**Comment by jeffreykegler** [comment]
This behavior is as expected, yes.

**Comment by jeffreykegler** [comment]
Oh, wait.  On closer look, this is a bit strange.

**Comment by jddurand** [comment]
Ok. In addition, I notice that the value returned by read() is always zero, when the doc says it returns the current physical input stream location. I mean this:

```
$r->read($input, 3)
        Position: 0, G1 location: 0, events: ^first
$r->resume(0)
        Position: 0, G1 location: 0, events: ^ANYTHING
```
Here I was excepting position to be ```3```

**Comment by jeffreykegler** [comment]
OK.  Here's what is going on.

The issue has nothing to do with earleme 0 -- you could duplicate it at another G1 location.  A "before lexeme" event is special.  It's underlying idea is that it's for external scanning, and that the user is going to read custom tokens and move the location to a location of the application's choice.  "Before lexemes" are *scanned* by L0, but not *read* by G1.  So here is what happens:

In the `read()`, Marpa sees that a `<first>` symbol is predicted, and issue a `^first` event.  This returns control to the user.  The prediction occurs before scanning ahead, so there is no `^ANYTHING` event.

2.)  In the resume, you are at position 0 in the input.  You now scan an `<ANYTHING>` lexeme, *but* because it has pause before set, it is not read into G1, so there will be no events for the location after the `<ANYTHING>`.  For convenience, the position is reset to location 0, at the beginning of the `<ANYTHING>` token.  An `^ANYTHING` event is generated, but no other events, because the new location is just a convenience -- you haven't created a new Earley set, just set a bookkeeping location.  The bookkeeping location is just a default, one you may immediately move without creating a new Earley set, and therefore without leaving any trace in the parse that you were ever there.

"Events" are descriptions of things which "happen" and not properties of the location setting.  "Lexeme before" events are a lot anomalous, because they happen only at the L0 level, and their effect is undone immediately, so that it is as if they never "happened".

**Comment by jddurand** [comment]
Thanks, understood.
What about the return value of read') ? shall I open another separate issue -;

**Comment by jeffreykegler** [comment]
Read returns 0 because an event occurs at location 0.
