### ISSUE TITLE
wichlist: line and column setter

### ISSUE THREAD

**Issue by jddurand** [jeffreykegler/Marpa--R2#261]
When doing a resume at a different position than current G1, it is easy to screen Marpa notions of line of column. So error reporting is not accurate anymore in terms of line and column number.
Therefore a setter, in case the caller is playing with input buffer and/or position in it, would be great.

**Comment by jddurand** [comment]
and of course I screwed the subject... please read "wishlist"

**Comment by jeffreykegler** [comment]
As you know, Marpa::R2 "wishes" are most likely to be fulfulled in Kollos.  I'll leave this in the wishlist for documentation.

**Comment by whitten** [comment]
Could some one explain what Kollos might happen to be?
I want to port MARPA:R2 to a different programming language.
Does that mean I should work with a base of Kollos instead of
the MARPA::R2 code on github ?

David Whitten
713-870-3834

**Comment by jeffreykegler** [comment]
This topic should really be discussed on the mailing list or the IRC channel.  My web page points to them: http://jeffreykegler.github.io/Marpa-web-site/ .

As a start on the answer, Kollos *will* be the what you want, but it is early in development.  Currently you can use the Libmarpa library directly.  It is in C89 C, and implements the complete parse engine.  The problem is that it is very low-level, even minimal upper-level sugar like symbol names must come from a wrapper.

**Comment by jeffreykegler** [comment]
@jddurand Same thing here.  OK if I copy this to Marpa::R3 and close?

**Comment by jddurand** [comment]
Yep! Thx

**Comment by jeffreykegler** [comment]
Copied to above referenced Marpa--R3 issue and closed.
